### ISSUE TITLE
Página não é redirecionada para principal ao editar cadastro do pedagogo

### ISSUE THREAD

**Issue by deividazevedo2** [deividazevedo2/Projeto-SISAP#1]
O redirecionamento da página não está sendo feito quando o cadastro é alterado.

**Comment by deividazevedo2** [comment]
Deve ser redirecionado para a página principal do sistema. A mensagem de dados alterados é mostrada, porém o redirecionamento não é feito, permanecendo na página de preenchimento dos dados pessoais.

**Comment by IndyPaula** [comment]
Foi Resolvido a tempo!
